import React from "react";
import Footer from "@/components/footer";
import {Urbanist} from "next/font/google";
import './globals.css'
import Navbar from "@/components/navbar";

const font = Urbanist({subsets:['latin']})

export const metadata = {
  title: 'Test Store',
  description: 'Generated by Gerchik',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
      <Navbar />
      {children}
      <Footer />
      </body>
    </html>
  )
}
